/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package add;

import admin.admindashboard;
import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import staff.staffdashboard;

/**
 *
 * @author Administrator
 */
public class viewtransactions extends javax.swing.JFrame {

    private String caller;
    private String loggedUser;

    
    /**
     * Creates new form viewtransactions
     */
    public viewtransactions(String caller, String loggedUser) {
    this.caller = caller;
    this.loggedUser = loggedUser;
    initComponents();

    // Set JTable columns to show all fields
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {},
    new String [] {
        "Transaction ID", "Customer ID", "User ID", "Service ID", "Notes",
        "Total Amount", "Payment Method", "Payment Status", "Laundry Status", "Date Created"
    }
    ) {
    @Override
    public boolean isCellEditable(int row, int column) {
        // Only editable: Notes, Total Amount, Payment Method, Payment Status, Laundry Status
        return column >= 4 && column <= 8;
    }
    });

    // 2️⃣ TableModelListener for auto-update
    jTable1.getModel().addTableModelListener(e -> {
        int row = e.getFirstRow();
        int column = e.getColumn();
        if(row < 0 || column < 0) return;

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int l_id = Integer.parseInt(model.getValueAt(row, 0).toString());   // Transaction ID
        int c_id = Integer.parseInt(model.getValueAt(row, 1).toString());   // Customer ID
        Object newValue = model.getValueAt(row, column);

        String columnName = model.getColumnName(column);
        String dbColumn = "";

        switch(columnName){
            case "Service": dbColumn = "s_id"; break; // optional: allow changing service
            case "Total Amount": dbColumn = "total_amount"; break;
            case "Notes": dbColumn = "note"; break;
            case "Payment Method": dbColumn = "payment_method"; break;
            case "Payment Status": dbColumn = "payment_status"; break;
            case "Laundry Status": dbColumn = "laundry_status"; break;
        }

        if(!dbColumn.isEmpty()){
            String sql = "UPDATE laundry SET " + dbColumn + " = ? WHERE l_id = ? AND c_id = ?";
            config cfg = new config();
            boolean success = cfg.updateRecord(sql, newValue, l_id, c_id);
            if(!success){
                JOptionPane.showMessageDialog(this, "Failed to update " + dbColumn);
            }
        }
    });

    // 3️⃣ Load all transactions
    loadTransactions();
}
   
   private void loadTransactions() {
    Connection conn = config.connectDB();
    if (conn == null) return;

    // Select all columns from laundry table
    String sql = "SELECT l_id, c_id, u_id, s_id, note, total_amount, " +
                 "payment_method, payment_status, laundry_status, date_created " +
                 "FROM laundry";

    try {
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear table first

        while(rs.next()) {
            Object[] row = new Object[] {
                rs.getInt("l_id"),                     // Transaction ID
                rs.getInt("c_id"),                     // Customer ID
                rs.getInt("u_id"),                     // User ID
                rs.getInt("s_id"),                     // Service ID
                rs.getString("note"),                  // Notes
                rs.getDouble("total_amount"),          // Total Amount
                rs.getString("payment_method"),        // Payment Method
                rs.getString("payment_status"),        // Payment Status
                rs.getString("laundry_status"),        // Laundry Status
                new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
                    .format(new java.util.Date(rs.getLong("date_created")*1000)) // Convert timestamp to readable
            };
            model.addRow(row);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading transactions: " + ex.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(192, 237, 232));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laundryyy-removebg-preview__1_-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("VIEW TRANSACTIONS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(185, 185, 185)
                .addComponent(jLabel2)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(192, 237, 232));
        jButton4.setText("SEARCH");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "l_id", "c_id", "u_id", "s_id", "total_amount", "notes", "payment_method", "payment_status", "laundry_status", "date_created"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Back");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
                                   
    String searchText = jTextField2.getText();

    Connection conn = config.connectDB();
    if (conn == null) return;

    // Search all relevant columns
    String sql = "SELECT l.l_id, l.c_id, l.u_id, l.s_id, l.note, l.total_amount, " +
                 "l.payment_method, l.payment_status, l.laundry_status, l.date_created " +
                 "FROM laundry l " +
                 "WHERE l.l_id LIKE ? OR l.c_id LIKE ? OR l.u_id LIKE ? " +
                 "OR l.s_id LIKE ? OR l.note LIKE ? OR l.total_amount LIKE ? " +
                 "OR l.payment_method LIKE ? OR l.payment_status LIKE ? OR l.laundry_status LIKE ?";

    try {
        PreparedStatement pst = conn.prepareStatement(sql);

        // Bind searchText to all placeholders
        for (int i = 1; i <= 9; i++) {
            pst.setString(i, "%" + searchText + "%");
        }

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        while(rs.next()) {
            Object[] row = new Object[] {
                rs.getInt("l_id"),
                rs.getInt("c_id"),
                rs.getInt("u_id"),
                rs.getInt("s_id"),
                rs.getString("note"),
                rs.getDouble("total_amount"),
                rs.getString("payment_method"),
                rs.getString("payment_status"),
                rs.getString("laundry_status"),
                new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
                    .format(new java.util.Date(rs.getLong("date_created")*1000))
            };
            model.addRow(row);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error searching transactions: " + ex.getMessage());
    }

    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        if ("admin".equals(this.caller)) {
        new admindashboard(loggedUser).setVisible(true);
        } else if ("staff".equals(this.caller)) {
         new staffdashboard(loggedUser).setVisible(true);
        }
        this.dispose();

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    // Launch the frame through PageLauncher so login is enforced
    java.awt.EventQueue.invokeLater(() -> {
        blocking.PageLauncher.launch(new addservices());
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
